/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MedicalAlgorithm } from './types.ts';

export const MEDICAL_TEMPLATES: MedicalAlgorithm[] = [
  {
    id: 'pph_prevention_management',
    name: '🔴 PPH Prevention & Management',
    description: 'Postpartum Haemorrhage protocol according to measured blood loss stages.',
    createdAt: 1771123200000,
    nodes: [
      {
        id: 'node_stage_1_header',
        type: 'annotation',
        label: 'STAGE 1: < 500mls ongoing blood loss OR woman compromised',
        icon: 'AlertCircle',
        x: 0,
        y: 0,
        width: 12,
        height: 1,
        notes: '',
        vocalConfirmation: false,
        vocalMessage: '',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'slate'
      },
      {
        id: 'node_call_help',
        type: 'button',
        label: '🚨 EMERGENCY BELL / NOTIFY MOH',
        icon: 'Bell',
        x: 0,
        y: 1.5,
        width: 4,
        height: 2,
        notes: 'Call for help immediately. Notify Anaesthetist and Registrar.',
        vocalConfirmation: true,
        vocalMessage: 'Emergency bell pressed. Calling for help.',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'rose'
      },
      {
        id: 'node_massage',
        type: 'button',
        label: 'Uterine Massage',
        icon: 'Activity',
        x: 0,
        y: 3,
        width: 3,
        height: 2,
        notes: 'Perform continuous uterine massage to stimulate contractions.',
        vocalConfirmation: true,
        vocalMessage: 'Uterine massage commenced.',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'amber'
      },
      {
        id: 'node_check_placenta',
        type: 'button',
        label: 'Check Placenta/Membranes',
        icon: 'Search',
        x: 3.5,
        y: 3,
        width: 3,
        height: 2,
        notes: 'Ensure complete delivery of placenta and membranes.',
        vocalConfirmation: true,
        vocalMessage: 'Placenta and membranes checked.',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'sky'
      },
      {
        id: 'node_follow_utero',
        type: 'button',
        label: 'Follow Algorithm - Uterotonics',
        icon: 'ArrowRightCircle',
        x: 0,
        y: 4.5,
        width: 3,
        height: 2,
        notes: 'Move to Uterotonics administration protocol immediately.',
        vocalConfirmation: false,
        vocalMessage: '',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'emerald'
      },
      {
        id: 'node_measure_blood',
        type: 'button',
        label: 'Measure Blood Loss',
        icon: 'Droplet',
        x: 3.5,
        y: 4.5,
        width: 3,
        height: 2,
        notes: 'Weigh swabs. Update total estimated blood loss every 15 mins.',
        vocalConfirmation: true,
        vocalMessage: 'Blood loss measured.',
        hasPrompt: true,
        promptQuestion: 'What is the current estimated blood loss (cumulative)?',
        promptPresetAnswers: ['< 500 ml', '500 - 1000 ml', '> 1000 ml', '> 1500 ml'],
        color: 'rose'
      },
      {
        id: 'node_iv_access',
        type: 'button',
        label: 'IV Access x 2',
        icon: 'Syringe',
        x: 0,
        y: 6,
        width: 3,
        height: 2,
        notes: 'Secure two large-bore IV cannulae.',
        vocalConfirmation: true,
        vocalMessage: 'IV access obtained.',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'indigo'
      },
      {
        id: 'node_empty_bladder',
        type: 'button',
        label: 'Empty Bladder',
        icon: 'Copy',
        x: 3.5,
        y: 6,
        width: 3,
        height: 2,
        notes: 'Insert indwelling catheter and secure urometer.',
        vocalConfirmation: true,
        vocalMessage: 'Bladder emptied.',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'amber'
      },

      // UTEROTONICS (Right Side)
      {
        id: 'node_utero_header',
        type: 'annotation',
        label: 'UTEROTONICS (1st & 2nd Line)',
        icon: 'Pill',
        x: 7.5,
        y: 1.5,
        width: 4.5,
        height: 1,
        notes: '',
        vocalConfirmation: false,
        vocalMessage: '',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'emerald'
      },
      {
        id: 'node_utero_1st_line',
        type: 'button',
        label: '1st Line Uterotonics',
        icon: 'Pill',
        x: 7.5,
        y: 3,
        width: 4.5,
        height: 2,
        notes: 'Syntometrine IM OR Ergometrine IM (0.5mg) OR Carboprost IM (250mcg) + Oxytocin IVI (40IU in 500mls)',
        vocalConfirmation: true,
        vocalMessage: 'First line uterotonics given.',
        hasPrompt: true,
        promptQuestion: 'Which 1st line uterotonic was administered?',
        promptPresetAnswers: ['Syntometrine IM', 'Ergometrine IM + Oxytocin IVI', 'Carboprost IM + Oxytocin IVI'],
        color: 'emerald'
      },
      {
        id: 'node_utero_2nd_line',
        type: 'button',
        label: '2nd Line: Carboprost IM (250mcg)',
        icon: 'Pill',
        x: 7.5,
        y: 5.5,
        width: 4.5,
        height: 2,
        notes: 'Every 15 mins up to max 8 doses.',
        vocalConfirmation: true,
        vocalMessage: 'Second line Carboprost administered.',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'sky'
      },
      {
        id: 'node_misoprostol_txa',
        type: 'button',
        label: 'Misoprostol 800mcg PR / TXA 1g IV',
        icon: 'Pill',
        x: 7.5,
        y: 8,
        width: 4.5,
        height: 2,
        notes: 'Misoprostol 4 tablets PR. Tranexamic Acid IV 1g (repeat if necessary after 30 mins).',
        vocalConfirmation: true,
        vocalMessage: 'Misoprostol and TXA administered.',
        hasPrompt: true,
        promptQuestion: 'Confirm administration',
        promptPresetAnswers: ['Misoprostol 800mcg PR Given', 'TXA 1g IV Given', 'Both Given'],
        color: 'rose'
      },

      // STAGE 2
      {
        id: 'node_stage_2_header',
        type: 'annotation',
        label: 'STAGE 2: approaching or >1000mls blood loss OR clinical concern',
        icon: 'AlertTriangle',
        x: 0,
        y: 10.5,
        width: 12,
        height: 1,
        notes: '',
        vocalConfirmation: false,
        vocalMessage: '',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'amber'
      },
      {
        id: 'node_stage_2_help',
        type: 'button',
        label: 'Registrar/Anaesthetist Present',
        icon: 'Users',
        x: 0,
        y: 12,
        width: 4,
        height: 2,
        notes: 'Ensure senior clinical help is present.',
        vocalConfirmation: true,
        vocalMessage: 'Senior help has arrived at bed side.',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'sky'
      },
      {
        id: 'node_fluid_replace',
        type: 'button',
        label: 'Fluid Replacement',
        icon: 'Droplet',
        x: 4.5,
        y: 12,
        width: 3.5,
        height: 2,
        notes: 'Commence rapid fluid warm replacement.',
        vocalConfirmation: true,
        vocalMessage: 'Fluid replacement running.',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'indigo'
      },
      {
        id: 'node_bloods_taken',
        type: 'button',
        label: 'Bloods Taken',
        icon: 'Activity',
        x: 8.5,
        y: 12,
        width: 3.5,
        height: 2,
        notes: 'FBC, Crossmatch, Coagulation screen.',
        vocalConfirmation: true,
        vocalMessage: 'Bloods taken and sent to lab.',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'rose'
      },
      {
        id: 'node_theatre',
        type: 'button',
        label: 'Transfer to Theatre?',
        icon: 'ArrowRightCircle',
        x: 0,
        y: 13.5,
        width: 4,
        height: 2,
        notes: 'If bleeding has not stopped, coordinate immediate transfer to theatre.',
        vocalConfirmation: true,
        vocalMessage: 'Preparing for theatre transfer.',
        hasPrompt: true,
        promptQuestion: 'Is the patient moving to theatre?',
        promptPresetAnswers: ['Yes - Transferring', 'No - Bleeding controlled'],
        color: 'violet'
      },

      // STAGE 3
      {
        id: 'node_stage_3_header',
        type: 'annotation',
        label: 'STAGE 3: >1500mls blood loss or ongoing clinical concern',
        icon: 'Flame',
        x: 0,
        y: 15.5,
        width: 12,
        height: 1,
        notes: 'CONSULTANT OBSTETRICIAN MUST BE INFORMED & ATTEND IF UNSTABLE',
        vocalConfirmation: false,
        vocalMessage: '',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'rose'
      },
      {
        id: 'node_review_cause',
        type: 'button',
        label: 'Review Cause (4 Ts)',
        icon: 'Search',
        x: 0,
        y: 17,
        width: 5.5,
        height: 2,
        notes: 'Tone. Trauma. Tissue. Thrombin.',
        vocalConfirmation: true,
        vocalMessage: 'Reviewing 4 Ts for cause of haemorrhage.',
        hasPrompt: true,
        promptQuestion: 'What is the suspected cause? (4 Ts)',
        promptPresetAnswers: ['Tone', 'Trauma', 'Tissue', 'Thrombin', 'Unknown'],
        color: 'amber'
      },
      {
        id: 'node_moh_protocol',
        type: 'button',
        label: 'Initiate MOH Protocol',
        icon: 'Bell',
        x: 6.5,
        y: 17,
        width: 5.5,
        height: 2,
        notes: 'Ensure Major Obstetric Haemorrhage protocol is fully initiated. Repeat TXA/Carboprost as needed.',
        vocalConfirmation: true,
        vocalMessage: 'MOH protocol initiated.',
        hasPrompt: false,
        promptQuestion: '',
        promptPresetAnswers: [],
        color: 'rose'
      }
    ],
    connections: [
      { id: 'conn_1', fromId: 'node_follow_utero', toId: 'node_utero_1st_line' },
      { id: 'conn_2', fromId: 'node_utero_1st_line', toId: 'node_utero_2nd_line' },
      { id: 'conn_3', fromId: 'node_utero_2nd_line', toId: 'node_misoprostol_txa' },
      { id: 'conn_4', fromId: 'node_stage_1_header', toId: 'node_stage_2_header' },
      { id: 'conn_5', fromId: 'node_stage_2_header', toId: 'node_stage_3_header' }
    ]
  }
];

